package org.vidge.util;

public enum VisualControlType {
	LABEL, TEXT, COMBO, CHECKBOX, DATE, TIME, TEXTAREA, IMAGE, OBJECT_EDITOR, EDITABLE_COMBO, PART_LIST_EDITOR, DEFAULT, COLOR, FONT, FILE, FOLDER, OBJECT_WIZARD, PASSWORD, NUMBER;
}
